{{- if .Values.rbac.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: dependency-controller-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
- apiGroups:
  - mnicloud.jp
  resources:
  - dependencies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mnicloud.jp
  resources:
  - dependencies/finalizers
  verbs:
  - update
- apiGroups:
  - mnicloud.jp
  resources:
  - dependencies/status
  verbs:
  - get
  - patch
  - update
{{- end -}}
